#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:14.16.1
pipelines:
  default:
       - step:
           name: Build and Test
           services:
             - docker
           script: 
              - curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              - chmod +x /usr/local/bin/docker-compose
              - docker-compose -v
              - yarn
              - yarn build
              - yarn fix
              - yarn test
           
